### ISSUE TITLE
Multiple `use flake` entries break caching

### ISSUE THREAD

**Issue by aisamu** [nix-community/nix-direnv#341] opened 2023-05-15 23:55 UTC
Someone suggested using multiple `use flake` invocations to compose flake "layers". 
It indeed works: the final result is the combination of the contents of both `devShells`! 

The unfortunate side-effect is that the caching mechanism no longer works.
Given an `.envrc` like the one below, every `direnv` invocation will trigger a cache renewal:

```
use flake ~/path/to/flake
use flake ~/path/to/another-flake
```

Inspecting the `.direnv` folder while nix-direnv runs revealed that the cache is being wiped, then populated with one entry, then finally being replaced with another entry (deterministically). 

What I suspect happens:

1. nix-direnv executes the first line. It generates and caches `flake`
2. nix-direnv executes the second line. The cache doesn't match. It wipes it, generates and caches `another-flake`
3. The direnv invocation finishes.

Then, on the next `direnv` invocation:
1. nix-direnv executes the first line. The cache is for line 2, so it doesn't match. It is then wiped, and it generates and caches `flake`...

Is there a way around this? 
Am I holding it wrong?

**Comment by bbenne10** [comment] 2023-05-16 13:16
While you are correct in your assessment of what is going on, I think I am going to say that this is not a bug and is - in fact - by design. The behavior you are seeing is (composing the flakes) - in some way - a bug in and of itself and I would not rely on this behavior to get everything correct in 100% of cases.

The correct way to handle this is to build a flake for the working directory that has a `devShell` that composes the two inputs. This shouldn't be terribly difficult in the general sense and is much more general and re-usable (both in and outside of a `nix-direnv` oriented workflow). It is a bit frustrating if both of your input flakes are local-only (i.e. not published via some public repository), as the file paths are not necessarily reproducible on all machines, but I believe that there is some work on nix and flakes' handling of relative paths (which I have admittedly not been keeping up with recently - having a newborn makes much of this hard to keep in my head already :P)

I'm going to close this, as I don't foresee us supporting this use-case without an external contributor doing the heavy lifting in converting the script to handle it (and then I may just push back that it is the wrong approach - I'm not sure I have done enough thinking on that front yet.)

**Closed by bbenne10** 2023-05-16 13:16 UTC

**Comment by aisamu** [comment] 2023-05-16 13:26
Not at all a problem, thanks for the thoughtful response!
