### ISSUE TITLE
nix-direnv cannot find nixpkgs with nix-2.4

### ISSUE THREAD

**Issue by deejayem** [nix-community/nix-direnv#119] opened 2021-11-03 14:42 UTC
I have a `.envrc` containing `use nix`, and a `shell.nix` containing `with import <nixpkgs> {}; stdenv.mkDerivation { name = "name"; nativeBuildInputs = [ (leiningen.override { jdk = jdk11; }) ]; }`

This works fine with nix 2.3, but after upgrading to `nix (Nix) 2.4pre-rc1`, I get the following when I `cd` into the directory:
`error: file 'nixpkgs' was not found in the Nix search path (add it using $NIX_PATH or -I)`

However, `nix-shell` still works, and if I use direnv without nix-direnv, that also works.

I'm on macos, and am using home-manager (`programs.direnv.nix-direnv.enable = true;`), if that's relevant.

```
$ nix-channel --list`
home-manager https://github.com/nix-community/home-manager/archive/master.tar.gz
nixpkgs https://nixos.org/channels/nixpkgs-unstable
```

The full output after using `cd` is as follows:
```
direnv: loading ~/src/foo/.envrc
direnv: using nix
error: file 'nixpkgs' was not found in the Nix search path (add it using $NIX_PATH or -I)
direnv: using cached derivation
direnv: eval /Users/djm/src/foo.direnv/cache-unknown
direnv: export +IN_NIX_SHELL +TEMPDIR +XDG_DATA_DIRS ~PATH
```

**Comment by Mic92** [comment] 2021-11-03 16:09
It seems that `NIX_PATH` is no longer set by your setup. In NixOS where I use flakes I usually solve it like this: https://github.com/Mic92/dotfiles/blob/f4711c4cd4fb717130da4e3e1a8ba6263fa20507/nixos/configurations.nix#L21

If you use channels make sure that they are included in your $NIX_PATH environment variable:

```console
$ ls -la $HOME/.nix-defexpr/channels
nixpkgs 
$ export NIX_PATH=$HOME/.nix-defexpr/channels
```

Sorry but this issue is not related to nix-direnv and nix-direnv cannot magically fix your setup. So I am closing this.
I hope the instructions above are helpful.

**Closed by Mic92** 2021-11-03 16:09 UTC

**Comment by mkhl** [comment] 2021-11-11 22:31
it seems that nix 2.4 is using default values when NIX_PATH is unset (NixOS/nix@ec9dd9a5aeb9b7fca170d86b8906ffac7e5ef057), and that because of this the default profile setup doesn't set NIX_PATH anymore

so the cause of this issue is that nix-direnv depends on and uses nix-2.3.16 instead of the nix it's installed with, and that version fails to deal with the setup provided by nix 2.4 (and generates warnings about newer config settings like `warning: unknown setting 'experimental-features'`)

**Comment by Mic92** [comment] 2021-11-12 08:57
> it seems that nix 2.4 is using default values when NIX_PATH is unset ([NixOS/nix@ec9dd9a](https://github.com/NixOS/nix/commit/ec9dd9a5aeb9b7fca170d86b8906ffac7e5ef057)), and that because of this the default profile setup doesn't set NIX_PATH anymore
> 
> so the cause of this issue is that nix-direnv depends on and uses nix-2.3.16 instead of the nix it's installed with, and that version fails to deal with the setup provided by nix 2.4 (and generates warnings about newer config settings like `warning: unknown setting 'experimental-features'`)

We upgraded nix-direnv to point to nix-2.4 now by default quite recently: https://github.com/NixOS/nixpkgs/pull/145236

**Comment by mkhl** [comment] 2021-11-12 09:50
perfect, then i'll just wait until that gets released and hits the channel. thank you!
