### ISSUE TITLE
nix flake archive tries to download unneeded flake inputs

### ISSUE THREAD

**Issue by maralorn** [nix-community/nix-direnv#298] opened 2023-02-07 14:35 UTC
When one builds a flake dev shell with `nix develop`, `nix print-dev-env` or `nix build .#devShells.<system>.default`  nix will only download flake inputs which are actually required during evaluation. nix-direnv uses `nix flake archive` which will copy a flake and all its dependencies to the store, even ones which are completely unneeded for the devShell.

This has the obvious but small downside of creating overhead. I had actually wondered before why loading the direnv shell triggered a download directly after successfully running `nix develop`.

It also has the less common but large downside that it does not work with unavailable flake inputs. My system-configuration flake depends on some private inputs which I don’t make available (via ssh access rights) to all my systems. This actually works quite fine for everything like `nixos-rebuild` or `nix develop` in my system config, but it does not work with `nix-direnv` for the described reason.

I am currently uncertain how this could be fixed.

I currently switched back to using the built-in use_flake of direnv, but I miss the caching. After reading https://github.com/direnv/direnv/wiki/Nix nix-direnv is still the only tool with caching and flake support.

**Comment by Mic92** [comment] 2023-02-07 15:48
I currently consider it a feature that I have all inputs available for offline use as the ttl of nix quickly evict those, which makes it hard to use it on a train. I don't know a different way to figure out what flakes are actually needed. In most projects people only add flakes they actually use so it's not a big issue in general. https://github.com/nix-community/nix-direnv/pull/275 might improve the situation a bit.

**Comment by bbenne10** [comment] 2023-02-15 13:36
@maralorn: It is worth noting that [devenv](https://github.com/cachix/devenv) recently added behavior that is pretty similar to what we are doing here, including caching. I have only passingly read their implementation and am unsure if it will address your concerns, but maybe have a look?

I am going to close this though. As has been stated: flake archival is a feature, not a bug.

**Closed by bbenne10** 2023-02-15 13:36 UTC
Labels: invalid, wontfix

**Comment by maralorn** [comment] 2023-02-16 23:00
I understand.

I had a look at devenv. It has it’s own caching support and flakes integration. The flakes integration uses nix-direnv instead of the devenv caching so sadly nothing is won that way.
