### ISSUE TITLE
Clash with `nix develop`

### ISSUE THREAD

**Issue by dschrempf** [nix-community/nix-direnv#150] opened 2022-03-03 09:41 UTC
Not sure if this is a `nix-direnv` issue, but anyways, I thought I report it somewhere. We can see where it belongs, and if it should be fixed or not.

I have `direnv allow` activated in a directory with a nix flake with a development shell. In this case, I have a Haskell project, and I use `haskellPackages.shellFor`, which is, I think, just a wrapper around `mkShell`. Everything works perfectly like so. However, when I want to stay in the environment while going to another directory, I have some trouble. First, I enter a `nix develop` shell, and assume the environment does not change, even when I leave the curreent working directory.

However, even within the `nix develop` shell, `direnv` unloads the environment, when I leave the working directory. So I always have to `direnv deny; nix develop`. Is this behavior expected? If not, can we do something against it? I am not sure if this is even possible, `direnv` would need to check if it is in a nix development environment.

Thanks!

**Comment by bbenne10** [comment] 2022-03-07 13:24
I'm not sure that there's really a technical fix for this. We hand off to direnv to manage unloads, which it is doing properly.
Since `nix develop` takes an installable as an argument and assuming a hierarchy like the following:

```
~/code/
  project_a/
    flake.nix
  project_b/
```

Where you want the `devShell` for  `project_a` active when inside `project_b`, could you not:

```
cd ~/code/
nix develop project_a
cd project_b
```

**Comment by bbenne10** [comment] 2022-03-07 14:49
I think I'm going to close this and I am unsure if there's anything to *do*.  direnv, nix-direnv, and nix develop are working as designed. This is an unfortunate overlap in workflows between the tools themselves that, in my opinion, requires workflow changes from the user to resolve.

I'd happily review a PR that introduces a fix for this, but I'm afraid such a PR is simply impossible here. If you have some insight on how this might be fixed in this project, please do speak up, but I'm afraid that you'll need to head over to the `direnv` repo and ask about a resolution there.

**Closed by bbenne10** 2022-03-07 14:49 UTC

**Comment by dschrempf** [comment] 2022-03-07 17:32
Thank you for looking into it anyways. I do not really have any insight. I was just reporting that `direnv` is basically changing the behavior of `nix develop`, which is weird, in a way.
