### ISSUE TITLE
Error when passing extra arguments to `use nix`

### ISSUE THREAD

**Issue by joncol** [nix-community/nix-direnv#168] opened 2022-04-25 08:37 UTC
Hi, after my latest NixOS system update (going to Nix 2.8, but I don't know if that's relevant), it seems I cannot pass extra arguments to `use nix` in `.envrc`.

For example, in a minimal project created using: `nix-shell -p niv --run 'niv init -b nixpkgs-unstable'`.

With `shell.nix`:
```nix
{ sources ? import ./nix/sources.nix, pkgs ? (import sources.nixpkgs { }) }:

{
  a = pkgs.mkShell { buildInputs = (with pkgs; [ hello ]); };
  b = pkgs.mkShell { buildInputs = (with pkgs; [ nyancat ]); };
}
```

and `.envrc`:
```bash
use nix -A a
```

I get the following error (when running `direnv allow` in the "project" directory):
```
direnv: loading ~/dummy/.envrc
direnv: using nix -A a
error: syntax error, unexpected invalid token, expecting ID or OR_KW or DOLLAR_CURLY or '"'

       at «string»:1:22:

            1| (import ./shell.nix).$}attribute}
             |                      ^
direnv: nix-direnv: renewed cache
direnv: export ~XDG_DATA_DIRS
```

**Comment by mdarocha** [comment] 2022-04-25 12:17
I think this is caused by the same error that was described in https://github.com/nix-community/nix-direnv/issues/162

This was fixed in https://github.com/nix-community/nix-direnv/commit/c35f4f013c2fb40a1fd221fecfce0f9c74383e4d, but unfortunately, no new version with this fix has been release yet.

Until a new nix-direnv release, you can either rollback to nix-direnv older than 2.0, or use a version from a specific commit with an overlay:
```nix
 nix-direnv = super.nix-direnv.overrideAttrs (old: rec {
    src = self.fetchFromGitHub {
      owner = "nix-community";
      repo = "nix-direnv";
      rev = "c35f4f013c2fb40a1fd221fecfce0f9c74383e4d";
      sha256 = "12opLFnNwC54T7RdBrCYWTuH20W2FVnNRN2MGIZkCpw=";
    };
  });
```

Disclaimer: This fixed my usecase with broken `use nix -p <list of packages>`. I'm not 100% sure this will fix your issue

**Comment by bbenne10** [comment] 2022-04-25 12:31
I'm not ENTIRELY sure that the fix mentioned above will resolve the issue. 
#162 was problematic in that the parsing fell back to an incorrect default case (`-*` rather than `*`).
This case already has a [matching case](https://github.com/nix-community/nix-direnv/blob/master/direnvrc#L278) and I believe the issue is in USING the custom attribute rather than assigning it.

**Comment by bbenne10** [comment] 2022-04-25 12:49
@joncol: I have just pushed a small commit that I *believe* will fix this issue, but do not have time to test right this moment.

Would you mind testing for me?
You can adjust the approach that @mdarocha mentions above to pull the commit in question as follows:

```nix
 nix-direnv = super.nix-direnv.overrideAttrs (old: rec {
    src = self.fetchFromGitHub {
      owner = "bbenne10";
      repo = "nix-direnv";
      rev = "e2341c4f2df70e89fc48406e0ecd4c7cc4491217";
      sha256 = nixpkgs.lib.fakeSha256;
    };
  });
```

Note that the sha256 is stubbed with `fakeSha256`. Run this and then copy the printed hash out of the failure report after the first (failed) build into the sha256 field. Once you replace with the correct computed sha, you should be able to test.

**Comment by joncol** [comment] 2022-04-25 13:04
@bbenne10: Both your fix, and the one linked to by @mdarocha above, seems to solve my problem. Thanks.

**Comment by bbenne10** [comment] 2022-04-25 13:17
Interesting. I wouldn't explect @mdarocha's solution to work, as the only thing that c35f4f013c2fb40a1fd221fecfce0f9c74383e4d fixes is a situation that your input wouldn't hit. `-A a` should hit [line 278](https://github.com/nix-community/nix-direnv/blob/master/direnvrc#L278), which will assign `a` to `attribute` and then effectively break out of the loop by shifting the arguments out from underneath `$#`.

Once done, we proceed to [line 336](https://github.com/nix-community/nix-direnv/blob/master/direnvrc#L336), which checks if there's a value in `$attribute` (which now contains `a` and so passes into the `else` statement and line 339 and append `"--expr" "(import ${nixfile}).$}attribute}"` to `extra-args` (where `nixfile` should be set to `shell.nix`). The typo following (the `$}`) prevents bash expansion from happening and so rather than extra args being `--expr "(import shell.nix).a"`, we end up with `--expr "(import shell.nix).$}attribute}"`, which is plainly wrong.

I've convinced myself that the fix I pushed is at least better and will merge that shortly. Additionally, I'll push a new `2.0.2` bugfix release (which I've been holding off on for fear I'll screw it up, but it seems simple enough :P)

**Comment by bbenne10** [comment] 2022-04-25 13:48
2.0.1 has been release containing both fixes mentioned here.

**Comment by mdarocha** [comment] 2022-04-25 13:50
Thanks! I made a PR to nixpkgs with a version bump: https://github.com/NixOS/nixpkgs/pull/170255

**Comment by bbenne10** [comment] 2022-04-25 13:55
Thank you! I will make a note to do that in the future so that I don't forget again.

**Comment by joncol** [comment] 2022-04-27 08:11
@bbenne10: I think this should be reopened.

When trying to use the overlay that you provided in my NixOS setup (using home-manager), I seem to have made some mistake, that caused the `direnvrc` file to not be placed in the `share/nix-direnv` sub-directory, in my nix store. End result of this was that `direnv allow` printed an error message like:
```
/home/jco/.config/direnv/direnvrc:1: /nix/store/1dg8gfn7d3saddlwqb02r7hc0ngmwr1h-source/share/nix-direnv/direnvrc: No such file or directory
```

I missed this the first time around, and thought everything was working, when it was instead bypassing `nix-direnv` completely, and instead only using normal `direnv`. This also explains why I thought everything was working with @mdarocha's repo, while you were correctly observing that this should _not_ work.

When directly copying the entire raw contents of your latest `direnvrc` into my `~/.direnvrc` (that should work, right?), I get this new error:
```
➜ dummynix git:(main)direnv allow
direnv: loading ~/code/dummynix/.envrc
direnv: using nix -A b
error: value is a function while a set was expected

       at «string»:1:1:

            1| (import ./shell.nix).b
             | ^
```

Minimal failing example is at https://github.com/joncol/dummynix

Sorry for the confusion.

**Comment by bbenne10** [comment] 2022-04-27 10:17
Yeah. This is why i have an open issue a out testing and adding regression tests. Ill need to cut another new release after hand testing your latest PR. Ill get to it shortly. Please be a bit patient with me. :)

**Comment by bbenne10** [comment] 2022-04-27 14:22
REALLY closed via #172, I believe. 
@joncol: Can you please give this a final test (using your dummynix repo) and then report final success or failure?

I will be cutting a follow up release again after closing, so I want to make sure that this *actually* fixes things this time :)

**Comment by joncol** [comment] 2022-04-28 05:21
Yes, it works for me now.

**Comment by joncol** [comment] 2022-04-29 08:24
@bbenne10: Another problem with extra args. Adding an option such as `-j4` (for increased parallelism) causes this error:
```
direnv: loading ~/work/scrive/new_frontend/.envrc
direnv: using nix -j4
error: getting status of '/home/jco/work/scrive/new_frontend/-j4': No such file or directory
direnv: nix-direnv: renewed cache
direnv: export ~XDG_DATA_DIRS
```
I added a [commit](https://github.com/joncol/dummynix/commit/5747dc6ce07ef6eb051682c59a536f0d24a78dd8) to the `dummynix` repository to illustrate the problem.

**Comment by bbenne10** [comment] 2022-04-29 14:01
We're kind of in a hard place here because we are sort of acting as if we're nix-shell, when we're actually a semi-frontend for `nix print-dev-env`. 

Ideally, I think we should probably do something like this (using `--` to mark what we're parsing a

`use nix -p foo shell.nix -- -j4 --foo=bar`

This allows a clear separation between OUR arguments and the arguments that are passed on.

Unfortunately, this is backwards incompatible and we'd need ANOTHER major version bump to handle it (not to mention the fact that the home-manager integration makes it difficult to know what version of nix-direnv you're getting at any particular nix invocation...)

In the short term, I am going to push a commit that adds support for "short form" arguments that'll fix this particular issue with `-j4` but WILL NOT fix `--foo bar` or such. Does that sound like a decent enough compromise?

**Comment by joncol** [comment] 2022-04-29 14:16
You also have to think of compatibility with ordinary `direnv`, right?

**Comment by bbenne10** [comment] 2022-04-29 14:30
Sort of?

We need to think about the backwards compat with old releases first and foremost.

Compatibility with vanilla `use nix`is imo a nice to have, but I dont mind dropping it for a better solution.

**Comment by bbenne10** [comment] 2022-05-01 10:57
Commit 891111e resolves this issue as written and extended here.

@joncol Thank you for fastidiously running headlong into things I didn't foresee (and then testing out solutions)
Should you find anything else, please open a new ticket. This one deserves a nap. :P

I've got some documentation updates I want to push and then going to release 2.1.0.

**Closed by bbenne10** 2022-05-01 10:57 UTC
Labels: bug

**Comment by joncol** [comment] 2022-05-06 05:47
@bbenne10, sorry to bother you again about this, but was a PR created against `nixpkgs` with the version update to 2.1.0?

**Comment by mdarocha** [comment] 2022-05-06 06:45
> @bbenne10, sorry to bother you again about this, but was a PR created against `nixpkgs` with the version update to 2.1.0?

I can make a PR later today if someone else didn't

**Comment by bbenne10** [comment] 2022-05-06 12:51
As noted above (since it is referenced in the changelog): PR opened. Thanks again for the reminder.
