### ISSUE TITLE
Allow interactive prompting for rebuilds

### ISSUE THREAD

**Issue by andir** [nix-community/nix-direnv#272] opened 2022-12-07 12:12 UTC
In some projects it might be good to know that you are about to rebuild a huge amount of packages for your shell environment. For most Nix projects that isn't the case because you either only build a few scripts or download everything from your binary cache. In the case that your configured binary caches do *not* have the paths you are looking for it would be great to receive an interactive prompt. The prompt should give you the list of paths that must be built while you can still decline the activation of the environment.

/cc @zimbatm maybe this goes into direnv territoriy?

**Comment by zimbatm** [comment] 2022-12-09 18:26
I'm not sure how to change direnv for that. nix-direnv introduces its own layer of caching. I guess nix-direnv could include a `nix-direnv-reload` command that also cleans that cache.

**Comment by bbenne10** [comment] 2022-12-09 19:18
We could allow the user to manually invalidate the cache, but that would be largely useless.
We already detect when the cache is out of date, but we don't have a way to specify a "version" of the cache to use as the cache includes the sha1sum of the (now invalid!) *old* cache.

As it stands, we either have a cache for the current version of the flake expression spit out by `nix print-dev-env` or not at all. There is some way we could change this to support explicit versioning of these environments, but my question is: if that's a thing you want, why not simply use `nix develop`, which provides explicit control over all environments and their lifetimes?

**Comment by andir** [comment] 2022-12-10 00:32
I think you are missing the point I was trying to make. I am proxying the annoyance of a user that disclosed this to me in private.
The problem is that they might want to work on a project and entering the environment will (silently, for the most part) cause a huge compilation/download/... that might not be desireable. Nix just goes out of your way and gets you your shell regardless of effort it hast to put into it (which is good). The question is if we can make it such that you get a "plan" phase before the execution. Just like you also have to allow a new envrc file.

**Comment by bbenne10** [comment] 2022-12-10 01:03
I understand exactly what you're asking for.
I'm not saying it is a bad thing to want, either.
I am simply saying that nix-direnv (and a direnv workflow overall) doesn't seem particularly conducive to achieving that goal.

If you want to explicitly opt in to using a nix-provided shell, it makes total sense to me to use `nix develop`.
That workflow is as follows (if you're unfamiliar):

```console
$ cd project/
$ nix develop
<nix goes and does its thing>
nix shell >  # Now you have the nix shell that you explicitly asked for
```

Is this not exactly the "plan phase" you're asking about?

The benefit of direnv + nix-direnv is that you get the up-to-date shell *without asking for it*.
The automatic rebuilding part is a feature - not a bug. If you don't want that feature, then I don't think that this is a tool you should be using - which is fine because `nix develop` also exists.

I guess the question I have is "What benefit does nix-direnv give you if you have to approve all rebuilds in a world where `nix develop` exists?"

**Comment by andir** [comment] 2022-12-10 10:13
`nix develop` doesn't get you any proper shell. It drops you into that bash that you might not normally be using. I don't think the 
"without asking" aspect is true as you have to allow the expression because it might cause harm to your computer. Unfortunately that only extends to the shell script part of `direnv`. Nix expressions might also have unwanted consequences (big downloads, builds, ...).

Thinking about this more I think `nix-shell` or `nix develop` should probably provide this interactive feature and/or the plan output to be consumed by other applications.

I generally think that doing the right thing is great but if we were to move into a world where we are more transparent to the user about what is going to happen (and give them a choice) developer friction might go down. You'll get some information on *why* that shell prompt might take longer for once.

**Comment by Mic92** [comment] 2022-12-10 17:36
> I think you are missing the point I was trying to make. I am proxying the annoyance of a user that disclosed this to me in private. The problem is that they might want to work on a project and entering the environment will (silently, for the most part) cause a huge compilation/download/... that might not be desireable. Nix just goes out of your way and gets you your shell regardless of effort it hast to put into it (which is good). The question is if we can make it such that you get a "plan" phase before the execution. Just like you also have to allow a new envrc file.

In your envrc you could add:

```bash
nix build --dry-run .#devShells.x86_64-linux.default
read -p "Do you want to load this shell? " -n 1 -r
echo    # (optional) move to a new line
if [[ $REPLY =~ ^[Yy]$ ]]; then
   use nix
fi
```

I feel however this is out of scope of what nix-direnv should provide itself...

**Comment by Mic92** [comment] 2022-12-10 17:38
> I generally think that doing the right thing is great but if we were to move into a world where we are more transparent to the user about what is going to happen (and give them a choice) developer friction might go down. You'll get some information on _why_ that shell prompt might take longer for once.

This is an issue with the old `nix-build` and `nix-shell` output. The new `nix build` actually gives you a progress bar quickly. And we use it for `nix-direnv` as opposed to direnv's implementation.

**Comment by zimbatm** [comment] 2022-12-11 23:44
I see the problem a bit more clearly now.

The problem is that if the cache gets invalidated, the user is on the hook for downloading an unbound amount of dependencies. Maybe they are on a metered or slow connection. As it stands, they don't have the choice to keep using the old environment.

This is true both for direnv and nix-direnv; both auto-reload whenever a dependency has changed.

Maybe a better design would inform the user and ask: "there is a new environment available, do you want to reload?". That keeps the user in control.

**Closed** 2023-01-09 17:03 UTC

**Comment by Mic92** [comment] 2023-07-04 19:59
We now go a better solution to the problem: https://github.com/nix-community/nix-direnv/pull/359#issue-1759527352
