### ISSUE TITLE
direnvrc: eval: <line-number>: syntax error near unexpected token `;'

### ISSUE THREAD

**Issue by rbreslow** [nix-community/nix-direnv#473] opened 2024-03-13 08:06 UTC
Multiple users in our organization have reported sudden issues with direnv. Seems to be resolved by clearing the direnv cache `rm -rf .direnv` and reloading the folder.

**User 1:**

```console
➜  Projects cd terraform
direnv: loading ~/Projects/terraform/.envrc
direnv: using flake
warning: Git tree '/Users/<username>/Projects/terraform' is dirty
evaluating derivation 'git+file:///Users/<username>/Projects/terraform#devShells.aarch64-darwin.default'direnv: ([/opt/homebrew/bin/direnv export zsh]) is taking a while to execute. Use CTRL-C to give up.
warning: Git tree '/Users/<username>/Projects/terraform' is dirty
direnv: nix-direnv: renewed cache
/Users/<username>/.nix-profile/share/nix-direnv/direnvrc: eval:1858: syntax error near unexpected token `;'
/Users/<username>/.nix-profile/share/nix-direnv/direnvrc: eval:1858: `            ;&'
direnv: export +AR +AS +CC +CONFIG_SHELL +CXX +DETERMINISTIC_BUILD +HOST_PATH +IN_NIX_SHELL +LD +LD_DYLD_PATH +MACOSX_DEPLOYMENT_TARGET +NIX_BINTOOLS +NIX_BINTOOLS_WRAPPER_TARGET_HOST_aarch64_apple_darwin +NIX_BUILD_CORES +NIX_CC +NIX_CC_WRAPPER_TARGET_HOST_aarch64_apple_darwin +NIX_CFLAGS_COMPILE +NIX_DONT_SET_RPATH +NIX_DONT_SET_RPATH_FOR_BUILD +NIX_ENFORCE_NO_NATIVE +NIX_HARDENING_ENABLE +NIX_IGNORE_LD_THROUGH_GCC +NIX_LDFLAGS +NIX_NO_SELF_RPATH +NIX_STORE +NM +PATH_LOCALE +PYTHONHASHSEED +PYTHONNOUSERSITE +PYTHONPATH +RANLIB +SIZE +SOURCE_DATE_EPOCH +STRINGS +STRIP +XDG_DATA_DIRS +ZERO_AR_DATE +__darwinAllowLocalNetworking +__impureHostDeps +__propagatedImpureHostDeps +__propagatedSandboxProfile +__sandboxProfile +__structuredAttrs +buildInputs +buildPhase +builder +cmakeFlags +configureFlags +depsBuildBuild +depsBuildBuildPropagated +depsBuildTarget +depsBuildTargetPropagated +depsHostHost +depsHostHostPropagated +depsTargetTarget +depsTargetTargetPropagated +doCheck +doInstallCheck +dontAddDisableDepTrack +mesonFlags +name +nativeBuildInputs +out +outputs +patches +phases +preferLocalBuild +propagatedBuildInputs +propagatedNativeBuildInputs +shell +shellHook +stdenv +strictDeps +system ~PATH
➜  terraform git status
zsh: command not found: git
```

**User 2:**

```console
<username>@MacBook-Pro-2 <company> % cd terraform/live/apollo/us-east-1/transfer/eff-sftp-out/
direnv: loading ~/src/freelancing/<company>/terraform/.envrc
direnv: using flake
/Users/<username>/.nix-profile/share/nix-direnv/direnvrc: line 211: local: -n: invalid option
local: usage: local name[=value] ...
direnv: nix-direnv: using cached dev shell
/Users/<username>/.nix-profile/share/nix-direnv/direnvrc: eval:1881: syntax error near unexpected token `;'
/Users/<username>/.nix-profile/share/nix-direnv/direnvrc: eval:1881: `            ;&'
direnv: export +AR +AS +CC +CONFIG_SHELL +CXX +DETERMINISTIC_BUILD +HOST_PATH +IN_NIX_SHELL +LD +LD_DYLD_PATH +MACOSX_DEPLOYMENT_TARGET +NIX_BINTOOLS +NIX_BINTOOLS_WRAPPER_TARGET_HOST_x86_64_apple_darwin +NIX_BUILD_CORES +NIX_CC +NIX_CC_WRAPPER_TARGET_HOST_x86_64_apple_darwin +NIX_CFLAGS_COMPILE +NIX_DONT_SET_RPATH +NIX_DONT_SET_RPATH_FOR_BUILD +NIX_ENFORCE_NO_NATIVE +NIX_HARDENING_ENABLE +NIX_IGNORE_LD_THROUGH_GCC +NIX_LDFLAGS +NIX_NO_SELF_RPATH +NIX_STORE +NM +PATH_LOCALE +PYTHONHASHSEED +PYTHONNOUSERSITE +PYTHONPATH +RANLIB +SIZE +SOURCE_DATE_EPOCH +STRINGS +STRIP +ZERO_AR_DATE +__darwinAllowLocalNetworking +__impureHostDeps +__propagatedImpureHostDeps +__propagatedSandboxProfile +__sandboxProfile +__structuredAttrs +buildInputs +buildPhase +builder +cmakeFlags +configureFlags +depsBuildBuild +depsBuildBuildPropagated +depsBuildTarget +depsBuildTargetPropagated +depsHostHost +depsHostHostPropagated +depsTargetTarget +depsTargetTargetPropagated +doCheck +doInstallCheck +dontAddDisableDepTrack +mesonFlags +name +nativeBuildInputs +out +outputs +patches +phases +preferLocalBuild +propagatedBuildInputs +propagatedNativeBuildInputs +shell +shellHook +stdenv +strictDeps +system ~PATH

<username>@MacBook-Pro-2 eff-sftp-out % ps
zsh: command not found: ps
```

All of these users are on macOS and have used the following instructions to install Nix, direnv, and nix-direnv:

```console
$ curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install
$ brew install direnv
$ echo eval "$(direnv hook zsh)" >>~/.zshrc
$ nix profile install nixpkgs#nix-direnv
$ echo 'source $HOME/.nix-profile/share/nix-direnv/direnvrc' >>~/.config/direnv/direnvrc
```

It's never happened on my machines, but I have a different set up with a laptop running nix-darwin and a NixOS desktop.

**Comment by simonzkl** [comment] 2024-03-13 09:23
I don't think this is related. It kinda sounds like zsh executing a bash script or something like that.

**Comment by Mic92** [comment] 2024-03-14 11:31
What bash version are you using?
Try to use if you can reproduce the issue with bash installed with nix.

**Comment by Mic92** [comment] 2024-03-14 11:46
It's also fine to use zsh as the interactive. It's about the version of bash in $PATH.
Just let them verify that `bash --version` returns something like 5.x i.e 5.2.26

**Comment by Mic92** [comment] 2024-03-14 12:06
There is actually a version check that should fail loudly if someone is using an too old bash version. Not sure why this check is not working properly. Otherwise you will need at least bash4. If you use install nix-direnv via home-manager that should already make sure that a new version of bash is put in place.

**Comment by Mic92** [comment] 2024-03-14 12:07
https://github.com/NixOS/nixpkgs/blob/7858badcfc69157fae059a616e989ca055f2829a/pkgs/tools/misc/direnv/default.nix#L23

**Comment by bbenne10** [comment] 2024-03-15 13:31
So I think this means that our suggestion of installing direnv from Homebrew (in the README) is inappropriate and needs to be re-written? I think the new suggestion should simply be to install `direnv` from nixpkgs?

```sh 
➜ nix shell nixpkgs#direnv

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
bash-3.2$ direnv exec . which -a bash
direnv: loading ~/code/personal/nix-direnv/.envrc
direnv: using flake
direnv: nix-direnv: using cached dev shell
/nix/store/4ia9i014ajl2l2cj75wzv5m463cisn4z-bash-5.2p26/bin/bash
/run/current-system/sw/bin/bash
/bin/bash
```

Does this show that the nixpkgs-provided `direnv` is wired to launch nixpkgs-provided `bash` too? If that's so - it should be enough to say that - on macOS - direnv should be installed from nixpkgs (Or you can get a supported bash version some other way - but I don't want to muddy the waters by going into it deeply. There's plenty of other complications in our documentation and I would like to avoid making it more complicated. :P )

**Comment by Mic92** [comment] 2024-03-16 15:17
I thought we fixed homebrew to also build with its own version bash? https://github.com/Homebrew/homebrew-core/commit/b800fa762f58844b4ede90fc084364ccfd28e563#diff-fb911d9f81daeaf60cca24c468e574351ef2dabe8845478bfedf1ac931587cb4R24

**Comment by bbenne10** [comment] 2024-03-16 15:22
Ah - I had forgotten that we'd done this.
Maybe it's not installed from a new enough revision?

**Comment by szlend** [comment] 2024-03-22 17:36
Possibly related to https://github.com/NixOS/nix/issues/10263?

**Comment by bbenne10** [comment] 2024-03-27 13:04
@iFreilicht: Which check are you talking about above? I *believe* @Mic92 is referring to [this check](https://github.com/nix-community/nix-direnv/blob/master/direnvrc#L64), which *should* be run unequivocally because it is checked *before* we execute `print-dev-env`. I would expect that the invoked bash version should be the same though?

**Comment by iFreilicht** [comment] 2024-03-27 13:06
Oh sorry, I was talking about [this one](https://github.com/NixOS/nixpkgs/blob/fea9c8f0fb69506f244d046117220c560a31c1ff/pkgs/stdenv/generic/setup.sh#L7). Disregard my comment about this, then.

**Comment by iFreilicht** [comment] 2024-03-27 13:32
> I would expect that the invoked bash version should be the same between the direnv invoked shell and the one behind the scenes in `print-dev-env`, but maybe I'm wrong?

This depends on how direnv is set up. I actually opened this issue in the direnv github because I had the same problem: https://github.com/direnv/direnv/issues/1256
And as it turned out I had two versions of direnv installed and hooked into the shell, with the one using system bash taking precedence.

direnv itself will use the exact bash path that was specified at compile time, or system bash if nothing was specified at compile time. So, when using direnv installed by Nix, you should be fine. But, if you have direnv installed from brew or some other source, then it will use system bash.

**Comment by bbenne10** [comment] 2024-03-27 13:46
> I thought we fixed homebrew to also build with its own version bash? [Homebrew/homebrew-core@b800fa7#diff-fb911d9f81daeaf60cca24c468e574351ef2dabe8845478bfedf1ac931587cb4R24](https://github.com/Homebrew/homebrew-core/commit/b800fa762f58844b4ede90fc084364ccfd28e563#diff-fb911d9f81daeaf60cca24c468e574351ef2dabe8845478bfedf1ac931587cb4R24)

Does this not satisfy the "specified at compile time"? This should say that the only bash to use is the one pointed at here, so we can be sure that the bash version we get is one we expect (and in fact - one from a known up-to-date source). and yet we've still got this bug report. So I'm not *entirely* sure that we've nailed down the entirety of the root cause here.

**Comment by iFreilicht** [comment] 2024-03-27 13:56
Hmm, it definitely should, the [relevant part of the makefile](https://github.com/direnv/direnv/blob/43f62188c2ec2ee11c879f8589ba24992715fa23/GNUmakefile#L52-L54) is pretty clear here.

But how do you know that's how the affected users installed direnv? In my case, the offending version was installed through asdf-vm via the asdf-direnv plugin.

**Comment by bbenne10** [comment] 2024-03-27 14:03
A co-worker just pointed out to me that `/usr/libexec/path_helper` is going to be the "root" cause of the problem in apple provided bash installs (maybe also apple-provided zsh installs? I haven't tested). `path_helper` puts the Apple provided `PATH` directories at the front no matter where they are in your current `PATH` so the Apple provided binaries are always found first if you invoke `path_helper`.

If you have:

1) A version of direnv installed without the tightening of the Bash version (via the `BASH_PATH` make variable in either nixpkgs or homebrew)  AND 
2) An apple provided bash shell as the first bash in `$PATH` AND 
3) Not modified your bash invocation to avoid calling `/usr/libexec/path_helper`

You'll run into this exact problem.

You're right to point out that we can't control how direnv gets installed - that's outside of our control (I just wish we could avoid triaging bugs that aren't our purview. Many - if not most - of our bugs these days seem to be improper setups or stuff like this that isn't *really* a thing we control...). 

The resolution here is - I think - to update direnv (if installed from nixpkgs or homebrew) **OR** to install a newer version of bash and avoid calling `/usr/libexec/path_helper` somehow **OR** to have nix/nix-darwin manage your shell for you (which avoids calling `path_helper` at all because it is known to cause issues exactly like this).

**Comment by danielo515** [comment] 2024-07-04 14:16
I was facing this same problem, and the issue was, indeed the bash version.
It will be nice to run a check for the bash version available and provide a better error message, given this is a known requirement

**Comment by bbenne10** [comment] 2024-07-04 15:43
[We check the version of the invoking shell.](https://github.com/nix-community/nix-direnv/blob/8ab6637a2f7c3240a089f2e0cf5dcefd483252c6/direnvrc#L68) [We document the version requirement.](https://github.com/nix-community/nix-direnv/?tab=readme-ov-file#installation)

I am unsure why the invoking shell isn't triggering. Happy to accept PRs improving the situation.

**Comment by danielo515** [comment] 2024-07-05 06:04
Ok, somehow I ended in this repo from devenv, but I think I didn't installed direnv from `nix-direnv` but plain direnv. Sorry for the confusion

**Comment by bbenne10** [comment] 2024-07-05 11:55
Devenv's got a version of nix-direnv built in. You'd need to speak with them about their "fork". Direnv also has a non-caching implementation of `use flake` and `use nix` built-in, which may or may not be interesting to you.

**Comment by bbenne10** [comment] 2024-07-21 18:21
Given that there is nothing here for the nix-direnv developers to do, I am closing this issue. I think we ought to pin either this issue or a similar one so that users can find it quickly and without reopening a similar one (provided that they actually *look*).

This is frustrating, but I do not know how we can check the versions of bash with which our dependencies are invoked :/

**Closed by bbenne10** 2024-07-21 18:21 UTC
